prepare:
  seed: 64
  dataset_path: data/datasets/serie02_plus_serie01_cv2
  out_path: out/prepared
  max_images: 500
  imbalance_ratio: 2
  img_shape: [1, 64, 64]
  train_split: 0.8
  apply_transforms: True
  batch_size: 16

train:
  seed: 653
  model_name: cnn_defect_detector_v1
  max_epochs: 8
  lr: 0.00015
  dropout: 0.3
  convs: [16, 32, 64, 128]
  hiddens: [256, 128]
  num_classes: 1 # binary classification
  num_workers: 4
  out_path: out/train
  model_save_path: out/train/models/model.ckpt

evaluate:
  out_path: out/evaluation

export:
  out_path: out/export
